"""add documents

Revision ID: d4113c00590c
Revises: 0d54799f70d9
Create Date: 2026-09-09 11:06:38.190768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4113c00590c'
down_revision: Union[str, Sequence[str], None] = '0d54799f70d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('external_document_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('reference_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('document_tag', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('document_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_documents_external_document_id'), 'documents', ['external_document_id'], unique=False)
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_documents_reference_no'), 'documents', ['reference_no'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('external_document_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('reference_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('document_tag', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_external_document_id'), 'document_pages', ['external_document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_job_id'), 'document_pages', ['job_id'], unique=False)
    op.create_index(op.f('ix_document_pages_page_no'), 'document_pages', ['page_no'], unique=False)
    op.create_index(op.f('ix_document_pages_reference_no'), 'document_pages', ['reference_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_pages_reference_no'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_page_no'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_job_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_external_document_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_documents_reference_no'), table_name='documents')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
